ZhangBlogIdea/ZhangBlogIdea/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import views as sitemap_views
from django.urls import path
from rest_framework.documentation import include_docs_urls
from rest_framework.routers import DefaultRouter

from blog.apis import PostViewSet, CategoryViewSet, TagViewSet
from blog.rss import LatestPostFeed
from blog.sitemap import PostSitemap
from blog.views import (
    IndexView, CategoryView, TagView, PostDetailView, SearchView, AuthorView,
)
from comment.views import CommentView
from config.views import LinkListView
from .custom_site import custom_site

# rest-framework 添加的路由
router = DefaultRouter()
router.register(r'post', PostViewSet, basename='api-post')
router.register(r'category', CategoryViewSet, basename='api-category')
router.register(r'tag', TagViewSet, basename='api-tag')

urlpatterns = [
                  path('', IndexView.as_view(), name='index'),
                  path('category/<int:category_id>/', CategoryView.as_view(), name='category-list'),
                  path('tag/<int:tag_id>/', TagView.as_view(), name='tag-list'),
                  path('post/<int:post_id>.html', PostDetailView.as_view(), name='post-detail'),
                  path('links/', LinkListView.as_view(), name='links'),
                  path('rss/', LatestPostFeed(), name='rss'),
                  path('sitemap.xml/', sitemap_views.sitemap, {'sitemaps': {'posts': PostSitemap}}),
                  path('search/', SearchView.as_view(), name='search'),
                  path('author/<int:owner_id>/', AuthorView.as_view(), name='author'),
                  path('comment/', CommentView.as_view(), name='comment'),
                  path('super_admin/', admin.site.urls, name='super-admin'),
                  path('admin/', custom_site.urls, name='admin'),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  path('api/', include(router.urls)),
                  path('api/docs/', include_docs_urls(title='HuanJianZhang apis')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

ZhangBlogIdea/comment/models.py
from django.db import models

from blog.models import Post


# Create your models here.
class Comment(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )
    target = models.CharField(max_length=100, verbose_name='评论目标')
    content = models.CharField(max_length=256, verbose_name='内容')
    nickname = models.CharField(max_length=50, verbose_name='昵称')
    website = models.URLField(verbose_name='网站')
    email = models.EmailField(verbose_name='邮箱')
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name='状态')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    @classmethod
    def get_by_target(cls, target):
        return cls.objects.filter(target=target, status=cls.STATUS_NORMAL)

    def __str__(self):
        return self.nickname

    class Meta:
        verbose_name = verbose_name_plural = '评论'

ZhangBlogIdea/comment/forms.py
import mistune
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    nickname = forms.CharField(
        label='昵称',
        max_length=50,
        widget=forms.widgets.TextInput(
            attrs={'class': 'form-control', 'style': "width: 60%;"}
        )
    )
    email = forms.EmailField(
        label='Email',
        max_length=50,
        widget=forms.widgets.EmailInput(
            attrs={'class': 'form-control', 'style': "width: 60%;"}
        )
    )
    website = forms.URLField(
        label='网站',
        max_length=100,
        widget=forms.widgets.URLInput(
            attrs={'class': 'form-control', 'style': "width: 60%;"}
        )
    )
    content = forms.CharField(
        label='内容',
        max_length=500,
        widget=forms.widgets.Textarea(
            attrs={'rows': 6, 'cols': 6, 'class': 'form-control'}
        )
    )

    def clean_content(self):
        content = self.cleaned_data.get('content')
        if len(content) < 10:
            raise forms.ValidationError('长度小于10个字符,不能提交,请完善一下,谢谢!')
        content = mistune.markdown(content)
        return content

    class Meta:
        model = Comment
        fields = ['nickname', 'email', 'website', 'content']

ZhangBlogIdea/comment/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.views.generic import TemplateView, ListView

from .forms import CommentForm


# Create your views here.
class CommentView(TemplateView):
    http_method_names = ['post']
    template_name = 'comment/result.html'

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(request.POST)
        target = request.POST.get('target')

        if comment_form.is_valid():
            instance = comment_form.save(commit=False)
            instance.target = target
            instance.save()
            success = True
            return redirect(target)
        else:
            success = False

        context = {
            'success': success,
            'form': comment_form,
            'target': target,
        }
        return self.render_to_response(context)

ZhangBlogIdea/ZhangBlogIdea/themes/bootstrap/templates/comment/block.html
<hr class="bg-success"/>
<div class="comment row">
    <form class="form-group col-md-8 offset-md-2" action="/comment/" method="POST">
        {% csrf_token %}
        <input name="target" type="hidden" value="{{ target }}"/>
        {% for comment in comment_form %}
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">{{comment.label }}</span>
            </div>
            {{ comment }}
        </div>
        {% endfor %}
        <div class="text-center">
            <input type="submit" class="btn btn-success" value="提交评论"/>
        </div>
    </form>

    <!--    评论列表-->
    <div>
        <ul class="list-group">
            {% for comment in comment_list %}
            <li class="list-group-item">
                <div class="nickname">
                    <a href="{{ comment.website }}">{{ comment.nickname }}</a>
                    <span>{{ comment.created_time }}</span>
                </div>
                <div class="comment-content">
                    {% autoescape off %}
                    {{ comment.content }}
                    {% endautoescape %}
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

ZhangBlogIdea/ZhangBlogIdea/themes/bootstrap/templates/comment/result.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>评论结果页</title>
    <style>
        body {text-align: center;}
        .result {
            text-align: center;
            width: 40%;
            margin: auto;
        }
        .errorlist {color: red;}
        ul li {
            list-style-type: None;
        }


    </style>
</head>
<body>
<div class="result">
    {% if success %}
    评论成功!
    <a href="{{ target }}">返回</a>
    {% else %}
    <ul class="errorlist">
        {% for field, message in form.errors.items %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    <a href="javascript:window.history.back();">返回</a>
    {% endif %}
</div>
</body>
</html>